In [ ]:
print('hello world')

hello world

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [ ]:
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [6]:
!pip install aspose.words
import aspose.words as aw

# load the PDF file
doc = aw.Document("/content/OutPatientReport_132016.pdf")

# convert PDF to Word DOCX format
doc.save("pdf-to-word.docx")

Collecting aspose.words
  Downloading aspose_words-22.3.0-py3-none-manylinux1_x86_64.whl (60.3 MB)
     |████████████████████████████████| 60.3 MB 1.2 MB/s
Installing collected packages: aspose.words
Successfully installed aspose.words-22.3.0

Exception ignored in: 'FieldInitializationWarning'
ImportError: the static field 'transparent' of type 'aspose.pydrawing.Brushes' is not initialized
Exception ignored in: 'FieldInitializationWarning'
ImportError: the static field 'alice_blue' of type 'aspose.pydrawing.Brushes' is not initialized
Exception ignored in: 'FieldInitializationWarning'
ImportError: the static field 'antique_white' of type 'aspose.pydrawing.Brushes' is not initialized